//updated til 12 august
export const videoTitleFullList = {
  "Ejercicio práctico de visualización": "ejercicio-practico-visualizacion",
  "Sesión de Mentalidad 26-06-2024": "M-26-06-2024",
  "Preguntas frecuentes": "preguntas-frecuentes",
  "Sesión de Mentalidad 24-07-2024": "M-24-07-2024",
  "Diseñando tu perfil de apps": "disenando-tu-perfil",
  "Una estructura para tu biografía": "estructura-biografia",
  "Introducción y temario": "Introduccion-y-temario",
  "Las doce reglas de las fotos": "doce-reglas-fotos",
  "Cosas esenciales para la primera cita": "cosas-esenciales-primera-cita",
  "Casos de éxito largo: 30 días de chat": "caso-exito-largo",
  "Sistema Lancémonos N.O.M.A.S": "sistema-lancemonos-nomas",
  "Estar presente por 24 horas - PDF": "estar-presente-por-24-horas",
  "Análisis de Interacciones 22-07-2024": "AI-22-07-2024",
  "Casos de éxito: mismo día y 2 citas": "caso-exito-rapido-y-medio",
  "Análisis de Cita con Problemas de Escalada":
    "analisis-cita-con-problemas-de-escalada",
  "Juego de Roles 22-05-2024": "JDR-22-5-2024",
  "Análisis de Interacciones 29-07-2024": "AI-29-07-2024",
  "Estar Presente es Darlo Todo": "estar-presente-darlo-todo",
  "Un esquema completo para tener citas": "esquema-para-tener-citas",
  "Sesión de Mentalidad 10-07-2024": "M-10-07-2024",
  "Intro a las interacciones casuales": "intro-interacciones-casuales",
  "Cómo invitarla a salir y posibles tests": "como-invitarla-a-salir",
  "Intro a los círculos sociales": "intro-circulos-sociales",
  "Juego de Roles 31-07-2024": "JDR-31-7-2024",
  "Las 10 reglas de los mensajes de texto Pt2":
    "diez-reglas-mensajes-texto-pt2",
  "Las Siete Reglas de la Mentoría": "siete-reglas-mentoria",
  "Las 10 reglas de los mensajes de texto": "diez-reglas-mensajes-texto",
  "Cómo Implementar el Darlo Todo": "como-implementar-el-darlo-todo",
  "Estructura del Programa Lánzate": "estructura-programa-lanzate",
  "El marco de nosotros": "marco-de-nosotros",
  "Visión de vida": "vision-de-vida-metas",
  "Dos Elementos para tener matches": "dos-elementos-para-tener-matches",
  "Juego de Roles 17-7-2024": "JDR-17-7-2024",
  "Esquema Inicio de conversación hasta cita":
    "esquema-inicio-de-conversacion-hasta-cita",
  "Construir una Rutina de Hábitos": "construir-rutina-habitos",
  "Construir atracción a través de mensajes": "construir-atraccion-apps",
  "10 Errores en mensajes de texto": "diez-errores-mensajes-texto",
  "Energía hacia arriba y hacia abajo": "energia-hacia-arriba-hacia-abajo",
};
